//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book()
        {
            this.comments = new HashSet<comment>();
        }
    
        public int book_id { get; set; }
        public string title { get; set; }
        public string edition { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> publication_id { get; set; }
        public string photo { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<int> subcategory_id { get; set; }
        public Nullable<int> pages { get; set; }
        public string description { get; set; }
        public string add_date { get; set; }
        public Nullable<byte> rate { get; set; }
        public Nullable<byte> availabilty { get; set; }
        public Nullable<int> member_id { get; set; }
        public string tags { get; set; }
        public string File { get; set; }
    
        public virtual author author { get; set; }
        public virtual publication publication { get; set; }
        public virtual subcategory subcategory { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }

        public HttpPostedFileBase uploadedImage { get; set; }

        public HttpPostedFileBase uploadedFile { get; set; }
        public int Category_Id { get; set; }
    }
}
