//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int comment_id { get; set; }
        public string comments { get; set; }
        public string comment_data { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual book book { get; set; }
        public virtual user user { get; set; }
    }
}
